script: 'bundle exec rake --trace $TASKS'

# Required by the go agent
before_install: 'sudo apt-get update'

install:
  - 'sudo apt-get install dnsutils'
  - 'bundle install --local --without development'

rvm:
  - ruby-1.9.3

env:
  - TASKS="travis:install_go spec:unit"

  - DB=mysql    TASKS="spec:integration:ruby_agent"
  - DB=postgres TASKS="spec:integration:ruby_agent"

  # Go agent integration tests do not need to test every DB flavor
  # since integration tests above already tested them
  - TASKS="travis:install_go spec:integration:go_agent"
